### ISSUE TITLE
suppress "viewbrowser" when viewing in browser

### ISSUE THREAD

**Issue by michield** [bramley/phplist-plugin-viewbrowser#10]
When the viewbrowser link is used the "View in browser" link is visible at the top. Would be nice to suppress it.

**Comment by bramley** [comment]
The plugin will now remove elements that are in the "viewbrowser" class when it generates the online version of the email. So if you add that class attribute to a surrounding element then the link will be suppressed

    <div class="viewbrowser">[VIEWBROWSER]</div>
