### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by Talkpoppycock** [bramley/phplist-plugin-viewbrowser#11]
I'm sure it's me, but I can't figure out where I can change the styling if the message. I appreciate that bt default the message will follow the styling of <a> tags and that I can have a specific  class for View in browser, but what class and where do I put it? An example would help.

**Comment by bramley** [comment]
I'm not sure what you are asking but the plugin configuration settings are on the Settings page, menu Config > Settings. See https://github.com/bramley/phplist-plugin-viewbrowser#configuration

**Comment by Talkpoppycock** [comment]
Hi Duncan,

 

What I’m asking is how to style the View in Browser message. Currently it is shown with the default styling for <a> tags. I would like to change this to something else.

 

Kind Regards,

Chris Rogers

 

Email: talkpoppycock@yahoo.co.uk

Tel: 01299 879239

Mob: 07779 152130

PPlease consider the environment before printing this email

**Comment by bramley** [comment]
Is this not clear?
You can change the styling of the link by specifying additional attributes for the <a> element, such as a specific class or a custom style. For example

class="myclass"

or

style="color: #ea5b0c;"

What have you tried that does not work?

**Comment by Talkpoppycock** [comment]
HI Duncan,

 

What you are saying is quite clear, but I haven’t tried it because I’m at a loss to understand where to put the class or styling.

I’ve tried putting [VIEWBROWSER] inside a tags like so <a  style="color: #ea5b0c;"> [VIEWBROWSER]</a> but did not over ride the default <a> styling.

Kind Regards,

Chris Rogers

 

Email: talkpoppycock@yahoo.co.uk

Tel: 01299 879239

Mob: 07779 152130

PPlease consider the environment before printing this email

**Comment by bramley** [comment]
The plugin replaces the placeholder with an a element, you do not create it, and will add the extra attributes, class or style, that you specify on the Settings page.

So just enter the attribute such as style="color: #ea5b0c;" in the field on the Settings page.

This applies only if you use the VIEWBROWSER placeholder. If you use VIEWBROWSERURL then you have control of the html anyway.

Also, please can you trim your earlier posts so that they include only your reply. If you are replying by email then just send your response.

**Comment by Talkpoppycock** [comment]
If I understand correctly, what you are saying is that I can alter the styling of <a> tags and that VIEWBROWSER will use that CSS. 

I already have my <a> tags styled as I want them, what I trying to achieve is a different styling for VIEWBROWSER.

**Comment by bramley** [comment]
>If I understand correctly, what you are saying is that I can alter the styling of <a> tags and that VIEWBROWSER will use that CSS. 

No, that is not what I am saying. Which part of my previous reply gives you that impression

>The plugin replaces the placeholder with an a element, you do not create it, and will add the extra attributes, class or style, that you specify on the Settings page.

Sorry, but apart from actually doing it for you, I don't think that I can help any more.

**Comment by Talkpoppycock** [comment]
What you didn’t say was “Have you got an up to date version of the View in Browser plugin?”, which I didn’t have. Now I have everything is clear. Sorry for the mix up. .  <https://github.com/notifications/beacon/AF797MpWm5YjHnd53cFlt7DPd00NMxYfks5pN-eXgaJpZM4GxUaf.gif>
