### ISSUE TITLE
Footer text not converted to HTML

### ISSUE THREAD

**Issue by samtuke** [bramley/phplist-plugin-viewbrowser#13]
It appears that footer text is not converted to HTML and line breaks are lost. Compare browser rendering vs mail client rendering in the attached screenshots. Perhaps the automatic newline to HTML conversion is not being applied?

Mail client (correct footer):
![screenshot from 2016-07-12 19-30-55](https://cloud.githubusercontent.com/assets/695422/16776877/9ed561e2-4867-11e6-80de-6c0b244b3fe6.png)

View in browser (incorrect footer):
![screenshot from 2016-07-12 19-30-46](https://cloud.githubusercontent.com/assets/695422/16776875/9eab131a-4867-11e6-90cd-55ea3deb8e26.png)

**Comment by bramley** [comment]
The "Unsubscribe" and "this link" links seem to show that the footer does contain html, i.e. is not simply plain text. Presumably there aren't any p tags in the footer and you are relying on new line characters being converted to p tags. 

The default message footer now does have p tags 
```
<div class="footer" style="text-align:left; font-size: 75%;">
<p>This message was sent to [EMAIL] by [FROMEMAIL]</p>
<p>To forward this message, please do not use the forward button of your email application, because this message was made specifically for you only. Instead use the <a href="[FORWARDURL]">forward page</a> in our newsletter system.<br/>
To change your details and to choose which lists to be subscribed to, visit your personal <a href="[PREFERENCESURL]">preferences page</a><br/>
Or you can <a href="[UNSUBSCRIBEURL]">opt-out completely</a> from all future mailings.</p>
</div>
```
Are you using an old configuration or explicitly removed p tags from the footer?

I can see cases when you don't want that new line conversion to happen as it could add extra vertical white spacing. I 'll need to reproduce your problem to see whether new line conversion creates any other problem. Generally I have tried to mimic what core phplist does, but in some cases that can be quite convoluted.

**Comment by bramley** [comment]
I think that you are using the message footer from phplist 2, which is plain text but with placeholders.
I have found the phplist code that deals with that.  The plain text is converted to html, then later the placeholders are replaced. So I will make the plugin do something equivalent.

**Comment by bramley** [comment]
Now fixed.

**Comment by samtuke** [comment]
Many thanks
