### ISSUE TITLE
anonymous broken in 3.2.5?

### ISSUE THREAD

**Issue by sculptex** [bramley/phplist-plugin-viewbrowser#14]
http://www.mydomain.com/lists/?m=19&p=view&pi=ViewBrowserPlugin

Error - A user uid must be specified

**Comment by bramley** [comment]
Have you enabled anonymous pages on the Settings page?

**Comment by sculptex** [comment]
that was the problem thanks. It worked before, it must have been on my test website (unless upgrading to 3.2.5 reset that setting)
