### ISSUE TITLE
Broken with phpList 3.3

### ISSUE THREAD

**Issue by julienlusson** [bramley/phplist-plugin-viewbrowser#15]
I've updated to phpList 3.3 and now I've got a 404 not found error.

**Comment by bramley** [comment]
Please can you explain exactly when the 404 error occurs, and why you think the plugin is not working? There are some problem with the new release of phplist concerning link tracking and that might be the cause.

**Comment by julienlusson** [comment]
I think in fact that it's not a problem of the plugin, but with phpList and link tracking. I've submitted a bug report: 
https://mantis.phplist.org/view.php?id=18522

**Comment by julienlusson** [comment]
PhpList 3.3.0 is broken... I close the (non) issue
