### ISSUE TITLE
viewbrowser class - complementary function (to render when viewed in browser)?

### ISSUE THREAD

**Issue by sculptex** [bramley/phplist-plugin-viewbrowser#16]
Using the class="viewbrowser" is great as I can place the [VIEWBROWSER] and related links in there so they only get shown when viewed in an email and suppressed when rendered as a (browser) webpage.

A complementary class could be added to do the opposite, that is render only in a browser and suppress it in an email.

This would be of great use where an email is sent to regular subscribers but also linked to from the website for unsubscribed visitors. The usual [VIEWBROWSER] link and unsubscribe options would appear in the email, but for the browser view, it would be more appropriate to have a link to a subscribe page instead for example.

* Unfortunately, the current viewbrowser class meaning is inverted as I guess its current name should be really be "hidebrowser" or "viewemail" as its shown in an email and suppressed when in a browser  (As a suggestion, maybe viewbrowser could be deprecated (but supported indefinitely), then replace it with hidebrowser and add hideemail as ongoing tags to use for their related purposes?)

**Comment by bramley** [comment]
When the plugin generates the email for displaying in a browser it has complete control over that, so it was simple to remove html elements  in a particular class.

That is not so easy when phplist is generating the email. At first glance I cannot see a place where the plugin can reliably identify and remove a chunk of text.

**Comment by sculptex** [comment]
Okay, many thanks for the response.
I guess its fair to close this then as it sounds like such a functionality would be outside of the scope of this plugin.
