### ISSUE TITLE
Unknown modifier '%' error

### ISSUE THREAD

**Issue by luuuciano** [bramley/phplist-plugin-viewbrowser#17]
Hi there!
I am trying this plugin, the only issue is that is showing several errors when someone uses the link.

Here they are:
`Sorry a software error occurred:
Please report a bug when reporting the bug, please include URL and the entire content of this page.

Warning: preg_match(): Unknown modifier '%' in /home/username/public_html/newsletter/admin/lib.php on line 1930
phpList version 3.3.1

Sorry a software error occurred:
Please report a bug when reporting the bug, please include URL and the entire content of this page.

Warning: preg_match(): Unknown modifier '%' in /home/username/public_html/newsletter/admin/lib.php on line 1930
phpList version 3.3.1 `

Any idea what is wrong? how to solve it?

Best regards!
Luciano

**Comment by bramley** [comment]
Have you created any user attributes? If so does one have a '/' character in it?

**Comment by luuuciano** [comment]
Ohhhh, you are right!
I have used "Name/s".... should I not use / there?
Will use just "Names" I think :-D

**Comment by bramley** [comment]
It is an error in core phplist not in the plugin, but the plugin reports php errors while phplist doesn't.

When you sent the email did phplist replace the placeholder "Name/s" properly?

**Comment by luuuciano** [comment]
Oh, I was not using [Name/s] in the template... and no, I have tried it and it is not replaced at all, just remains [Name/s]

**Comment by bramley** [comment]
Raised a pull request on core phplist https://github.com/phpList/phplist3/pull/162
