### ISSUE TITLE
Archive option

### ISSUE THREAD

**Issue by bartkummel** [bramley/phplist-plugin-viewbrowser#18]
Hi Duncan,

I'm looking for some archive solution for my PHPList-based newsletter. I know there's some "hack" which can be downloaded from a website of a photographer, but I don't want to depend on a hack, I'd rather use a properly maintained plugin.

I found your plugin and it works well for viewing a single message in the browser. I think this plugin can be used to create an archive with little effort. The only thing you need to add is a way to generate a list of all messages sent to the list the user is subscribed to. I'd love to see such a feature added to your plugin. 

Best regards,
Bart Kummel

**Comment by bramley** [comment]
That is possible but your requirement might be at the simpler end of things. I would expect that other people might want to restrict the lists that can be used in this way rather than including all campaigns that have been sent.
Also, to allow "public" access that allows anyone, not just a subscriber, to view a campaign.

I will look into this to see what is needed but can you explain how you see an archive page being accessed. Is it from a link in an email, for example?

**Comment by bartkummel** [comment]
Hi Duncan,

Thanks for your quick reply. Yes, I understand that my requirements might be rather simple, but other people might expect more complex things. That said, why not start with the simple case? It might be sufficient for a lot of people. 

As for my own requirements:

- I don't need public acces. To the contrary: I explicitly don't want anonymous people to view the archive.
- It would be nice if people could navigate to the archive after logging in, but if it is easier to only be able to view the archive when accessed from a link in an email, that's fine by me.
- I would also like to be able to create a link to a specific archived message from the list. (E.g. for linking to a previous newsletter.)

Best regards,
Bart

**Comment by bramley** [comment]
> It would be nice if people could navigate to the archive after logging in,

This would apply only to phplist administrators, presumably only you and one or two more. The only way that subscribers could see the page is through a link in a campaign that contains their UID.

> I would also like to be able to create a link to a specific archived message

You can do that already with a URL of the format
`http://www.mysite.com/lists/?m=999&p=view&pi=ViewBrowserPlugin&uid=[UID]`

[UID] is a standard placeholder that is processed by phplist.

**Comment by bramley** [comment]
> [UID] is a standard placeholder that is processed by phplist.

I was wrong about that, the placeholder is [USERID].

**Comment by bartkummel** [comment]
@bramley Great that I already can create that URL! Still, it would be nice to have a way to generate that URL by a placeholder. Something like `[LINK_TO_MESSAGE 999]`.

**Comment by bramley** [comment]
I have added an archive page to show campaigns sent to the subscriber. At present it is on a separate branch in Github so you can install it through phplist using  https://github.com/bramley/phplist-plugin-viewbrowser/archive/archive.zip

The presentation of the listing is a bit simple but you are able to customise the css. See the documentation page https://resources.phplist.com/plugin/viewinbrowser

I have also extended the VIEWBROWSER placeholder to allow a different campaign to be specified, e.g. [VIEWBROWSER:123].

**Comment by bartkummel** [comment]
@bramley Wow, this is exactly what I need. Great! Thank you so much for adding this functionality in such a short time! I've done a quick test, and it all works as described. 

One little enhancement request: it is a bit difficult to find the ID for a past newsletter. Since you already added a "campaign archive" to the admin area, I think it should be fairly easy to add the ID to that table. 

And a question: what is the best way to localize the user facing parts of the archive page? My readers are Dutch, so it would be nice to have the archive page localized. I think I should be able to do this myself, isn't it?

**Comment by bramley** [comment]
phplist doesn't yet provide translations of text within plugins. But you can try adding your own translations, which I think will be kept when the core phplist translations are updated. You will need to insert rows into the phplist_i18n table. I will try to create a list of all the translatable items.

**Comment by bartkummel** [comment]
Hi @bramley ,

Thanks again. The archive function works like a charm! I have only three minor things left:

1. I ran the SQL-script from your `translate.txt`, but it doesn't seem to work. I assume I have to change the "lan" values to "nl", as well as adding the Dutch translations, right?
2.  I'm still looking for an easy way to look up the ID of past emails. It would be great to be able to view them in the admin archive page.
3. When linking to a past issue, using the `[VIEWBROWSER:123]` or `[VIEWBROWSERURL:123]` placeholder, I'm missing the option to use custom link text. `[VIEWBROWSER:123]` always inserts the default text. I can use `[VIEWBROWSERURL:123]` of course, but this will show the complete URL in the text. I tried to use the `[VIEWBROWSERURL:123]` placeholder inside the edit link dialog in the WYSIWYG editor, but that doesn't work. Is there a way to get `[VIEWBROWSERURL:123]` working with the edit link dialog? Or is it perhaps possible to add the link text as a third attribute? Something like `[VIEWBROWSERURL:123:last weeks newsletter]`, which then expands to `<a href="http://foobar.com/?pi=ViewBrowserPlugin&p=view&m=62&uid=123456789abcdef">last weeks newsletter</a>`.

Again: thanks for adding this feature in such a short time frame. I really appreciate it. 

Best regards,
Bart

**Comment by bramley** [comment]
Yes, you need to change the language to "nl" and change the translation field. What do you mean by doesn't seem to work? Did the sql query execute correctly? If so then you then need to logout and login again.

There is a new release on GitHub so just update the plugin using its original URL (the one containing master as part of the URL). The campaign id is now displayed.

You are right that [VIEWBROWSER:123] isn't that useful using the same link text as for [VIEWBROWSER]. But [VIEWBROWSERURL:123] should work in the link dialog in CKEditor but you need to select "other" for the protocol.  Here is a screenshot of the resultant html

![image](https://user-images.githubusercontent.com/3147688/32396331-a8307aa8-c0dc-11e7-840b-bc11f93c500e.png)

**Comment by bartkummel** [comment]
Awsome, @bramley! I had to tinker a bit with the CSS to get the archive table displaying as a proper table, but now it works. The archive CSS I have now looks like this:
```css
/* this hides the first column for normal users, but keeps it visible in the admin area */
.content #archive .cell-1 {
  display: none;
}

/* Giving the columns a sensible width */
#archive .cell-1 {
  width: 5%;
}
#archive .cell-2 {
  width: 75%;
}
#archive .cell-3 {
  width: 15%;
}

/* Make sure the cells do actually display as cell */
#archive .cell-1, #archive .cell-2, #archive .cell-3 {
  display: table-cell;
}
#archive .table {
  display: table;
  width: 60%;
}
#archive .innertable {
  display: table;
  width: 100%;
  height:100%;
}
#archive .line {
  display: table-row;
}
#archive .heading {
  font-weight: bold;
}
```
The translation did work after logging out and in again, sorry to bother you with that. Should have tried this myself.

I'll try the "other" protocol on a later time, thanks for the tip. Wasn't aware of that option.

Again, thank you for your fast changes and good support!

Best regards,
Bart

**Comment by bramley** [comment]
Can you give me a copy of your translations? I'm looking at a method of including translation files in the plugin that are updated automatically.

**Comment by bartkummel** [comment]
Sure:
```sql
INSERT INTO `php_i18n` (`lan`, `original`, `translation`) VALUES
('nl', 'A numeric template image id must be specified', 'Er moet een nummeriek template id worden opgegeven.'),
('nl', 'Archive of campaigns', 'Nieuwsbrievenarchief'),
('nl', 'A user uid must be specified', 'Er moet een gebruikers-uid worden opgegeven.'),
('nl', 'The xsl extension must be installed', 'De XSL uitbreiding moet geïnstalleerd zijn.'),
('nl', 'A numeric message id must be specified', 'Er moet een numeriek bericht id worden opgegeven.'),
('nl', 'CommonPlugin must be installed', 'CommonPlugin moet geïnstalleerd zijn.'),
('nl', 'No campaigns found', 'Geen nieuwsbrieven gevonden'),
('nl', 'View in browser', 'Bekijk in de browser'),
('nl', 'The text of the link', 'De tekst van de link'),
('nl', 'email archive', 'emailarchief'),
('nl', 'The text of the archive link', 'De tekst van de link naar het archief'),
('nl', 'Additional attributes for the html &lt;a> element', 'Extra attributen voor het html &lt;a> element'),
('nl', 'Whether the plugin should provide an anonymous page', 'Of de plugin een anonieme pagina beschikbaar moet stellen'),
('nl', 'Plugins to be used when creating the email. Usually leave this unchanged.', 'Plugins die gebruikt worden om de email aan te maken. Kan meestal ongewijzigd worden gelaten.'),
('nl', 'CSS to be applied to the campaign archive page', 'CSS die wordt toegepast op de archief-pagina'),
('nl', 'Campaign archive', 'Nieuwsbrievenarchief')
```

**Comment by bramley** [comment]
Thanks. I have incorporated your translations and CSS changes into the plugin.
