### ISSUE TITLE
Additional parameters causes 404 error

### ISSUE THREAD

**Issue by hktang** [bramley/phplist-plugin-viewbrowser#21]
Hi,

Thanks for creating this useful plugin. 

On the anonymous view, it seems setting an additional parameter on the query string causes a 404 error. For example, appending a `utm_source` breaks the page.

    /lists/?m=123&p=view&pi=ViewBrowserPlugine&utm_source=twitter

Is it possible to discard the unwanted parameters and return the view correctly?

**Comment by bramley** [comment]
You have mistyped the plugin name in the URL.
