### ISSUE TITLE
Problem with URL

### ISSUE THREAD

**Issue by cayoumedia** [bramley/phplist-plugin-viewbrowser#5]
Hello,

i have Problem with URL in Email:

?m=1&amp;uid=chmrlto65nfsvtcwv1nfhabssrne58bauifiqrcmk13gnj6clr&amp;p=view&amp;pi=ViewBrowserPlugin

&amp; -> &

You Unterstand? Thanks...

**Comment by cayoumedia** [comment]
"&amp" -> &

**Comment by bramley** [comment]
I think that Github is interfering with your url.
The plugin uses `&amp;` for the html format message because the url is within html.  For the text format message it uses simply `&`. Why is that a problem?

**Comment by cayoumedia** [comment]
if you click on the link and the "&" is not masked, the Subcribe page displayed instead of the template....

**Comment by bramley** [comment]
Sorry I don't understand you. You will need to provide the email that is the problem. Please copy/paste part of the html to explain. See https://guides.github.com/features/mastering-markdown/ for how to tell github to treat the html as code.

**Comment by cayoumedia** [comment]
screen? you unterstand?
![unbenannt-1](https://cloud.githubusercontent.com/assets/10852049/6046234/7b607396-aca0-11e4-8554-6156fb7649c3.jpg)

**Comment by bramley** [comment]
I asked to see the email to see what the html looks like.
If you don't give me all the information then I won't be able to help you.

**Comment by cayoumedia** [comment]
ok sorry ... just once click on the link and then again on the link ...

<addr><a href="http://www.art-cover.eu/lists/?m=1&amp;uid=chmrlto65nfsvtcwv1nfhabssrne58bauifiqrcmk13gnj6clr&amp;p=view&amp;pi=ViewBrowserPlugin">Wenn dieser Newsletter nicht richtig angezeigt wird, klicke hier.</a>

----------------------------------

Hallo Sebastian Schmiedel,

die ist für einen Test...

Mit freundlichen Gruß

</addr>

**Comment by bramley** [comment]
So the link in the email works correctly, but it is the link in the web page that is wrong?
As I asked, please provide the source of the email so that I can see the html.
Which placeholder are you using [VIEWBROWSER] or [VIEWBROWSERURL]?

**Comment by cayoumedia** [comment]
no in the email is the same problem to find already .... i use [VIEWBROWSER]

**Comment by cayoumedia** [comment]
<addr><html dir="ltr">
    <head>
        <title></title>
    </head>
    <body>
        <p>[VIEWBROWSER]</p>
        <p>----------------------------------</p>
        <p>Hallo [VORNAME] [NACHNAME],</p>
        <p>die ist f&uuml;r einen Test...</p>
        <p>Mit freundlichen Gru&szlig;</p>
        <p>Sebastian Schmiedel</p>
    </body>
</html>
</addr>

**Comment by bramley** [comment]
Try making this change to the plugin code file ViewBrowserPlugin.php
change line 71 from

    return $url . '?' . http_build_query($params);
to

    return $url . '?' . http_build_query($params, '', '&');
Then send another test email.

**Comment by cayoumedia** [comment]
yes thanks ^^

**Comment by bramley** [comment]
Does that change make the urls correct? If so then I will update the plugin code.

**Comment by cayoumedia** [comment]
yes work perfect...thanks
