### ISSUE TITLE
not found view.php url in 3.0.7 version when the link is clicked

### ISSUE THREAD

**Issue by Danjavia** [bramley/phplist-plugin-viewbrowser#7]

**Comment by bramley** [comment]
Is this a new install of phplist and the plugin or have you used the plugin on an earlier release of phplist? 

If you follow the steps here https://github.com/bramley/phplist-plugin-viewbrowser#install-viewphp-phplist-306-and-earlier (although you shouldn't need to) then the link click should work.

**Comment by Danjavia** [comment]
Yes all it's done thanks!
