### ISSUE TITLE
Error when viewing the newsletter

### ISSUE THREAD

**Issue by drwebbe** [bramley/phplist-plugin-viewbrowser#8]
Hello,

I get errors online when viewing the newsletter at http://mailing.cu-lan.be/lists/?m=1&p=view&pi=ViewBrowserPlugin&uid=20ff287f8253d8c9e27715b695dd6299

Sorry a software error occurred:
Please report a bug when reporting the bug, please include URL and the entire content of this page.
Warning: preg_match(): Unknown modifier 'V' in /var/www/vhosts/cu-lan.be/mailing.cu-lan.be/lists/admin/lib.php on line 1642 phpList version 3.0.12

Kind regards,
Kurt

**Comment by bramley** [comment]
I guess that you have a user attribute that includes a '/' or some other non-alphanumeric character.

The code that the error message points to is in phplist itself not the plugin. The same error should have occured when phplist sent the email, but it disables error reporting. In the email you received is there a placeholder that has not been replaced?

**Comment by drwebbe** [comment]
Hello Bramley,
I had a '/' in in user attributes.
I renamed the attributes and now every works just fine !
http://mailing.cu-lan.be/lists/?m=1&p=view&pi=ViewBrowserPlugin&uid=20ff287f8253d8c9e27715b695dd6299
Thanks a lot for you great work !!!!!!!!!!
Kind regards,
Kurt
