### ISSUE TITLE
Error when using ViewBrowser Plugin

### ISSUE THREAD

**Issue by alemao59** [bramley/phplist-plugin-viewbrowser#9]
Hi all,

i am getting the following error when using the ViewBroser plugin

Sorry a software error occurred:
Please report a bug when reporting the bug, please include URL and the entire content of this page.

Fatal error: Class 'ViewBrowserPlugin_ContentCreator' not found in /lists/admin/plugins/ViewBrowserPlugin/view.php on line 28
phpList version 3.0.12
php 5..5.

Any ideas what causes this error? Thanks.

**Comment by bramley** [comment]
Have you enabled CommonPlugin on the Manage Plugins page?

**Comment by alemao59** [comment]
Yes the CommonPlugin is installed and enabled.

Am 17.09.2015 um 10:45 schrieb Duncan Cameron:

**Comment by bramley** [comment]
Is it the latest version of CommonPlugin? Otherwise, I don't really have any ideas why it is not working.

**Comment by alemao59** [comment]
I have updated the CommonPlugin and now its working beside this warning:

*Strict Standards*: date(): It is not safe to rely on the system's 
timezone settings. You are *required* to use the date.timezone setting 
or the date_default_timezone_set() function. In case you used any of 
those methods and you are still getting this warning, you most likely 
misspelled the timezone identifier. We selected 'Europe/Berlin' for 
'CEST/2,0/DST' instead 
in*/homepages/4/d11638473/htdocs/emir-cms/lists/admin/lib.php*on line*167*
phpList version 3.0.12

Sorry a software error occurred:
Pleasereport a bug <http://mantis.phplist.com/>when reporting the bug, 
please include URL and the entire content of this page.



Am 17.09.2015 um 11:35 schrieb Duncan Cameron:

**Comment by bramley** [comment]
> I have updated the CommonPlugin and now its working 

The installation instructions explicitly said to upgrade to the latest version of Common Plugin. 

As the message says, you need to set your timezone. You can do that by adding a line to your config file similar to this

````
date_default_timezone_set('America/Los_Angeles');
````
see http://php.net/manual/en/function.date-default-timezone-set.php

**Comment by alemao59** [comment]
Thanks for your help. Its working fine now.

Am 17.09.2015 um 12:37 schrieb Duncan Cameron:
